#Write a Python function that accepts a list of strings and returns a new list containing only the strings that start with the letter 'a'.
# fruit = list(input("enter the fruits name:").split())

# fruits=[string for string in fruit if string.lower().startswith('a')]

# print(fruits)


#------------------------------------------------------------------------------
#Write a Python function that takes a list of numbers and returns the sum of all the odd numbers in the list.
# number=list(map(int,input("enter the number: ").split()))

# odd=sum(num for num in number if num % 2 != 0 )
# print(odd)


#---------------------------------------------------------------------------------
#Write a Python function that accepts a list of numbers and returns a new list with each element squared.

# number=list(map(int,input("enter the number: ").split()))

# sq=[num*num for num in number]
# print(sq)



#----------------------------------------------------------------------------------
#Write a Python function that takes a list of words and returns the length of the longest word in the list.
# word=list(input("enter a many words:").split())

# words=max(len(mword) for mword in word)

# print(words)

